name: Build macOS DMG

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      run: |
        brew install python@3.10
        # alias 설정
        echo 'export PATH="/opt/homebrew/opt/python@3.10/bin:$PATH"' >> $GITHUB_ENV
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Setup FFmpeg
      run: brew install ffmpeg

    - name: Build Executable
      run: |
        source venv/bin/activate
        # 모든 파일을 루트로 복사
        cp src/*.py .
        cp src/*.pyw .
        
        # 빌드
        pyinstaller --noconfirm --onedir --windowed --name "HDR_to_SDR_Converter" \
          --add-data "gui.py:." --add-data "conversion.py:." --add-data "utils.py:." \
          --add-binary "$(which ffmpeg):." \
          --add-binary "$(which ffprobe):." \
          main.pyw

    - name: Create DMG
      run: |
        # 1. 빌드 결과물(폴더 내 .app)을 경로 불문하고 찾아내서 복사
        mkdir -p dmg_tmp
        APP_PATH=$(find dist -name "*.app" | head -n 1)
        if [ -z "$APP_PATH" ]; then echo "App not found!"; exit 1; fi
        cp -r "$APP_PATH" dmg_tmp/
        
        # 2. 링크 생성
        ln -s /Applications dmg_tmp/Applications
        
        # 3. 압축
        hdiutil create -volname "HDR_to_SDR" -srcfolder dmg_tmp -ov -format UDZO dist/HDR_to_SDR_Converter.dmg

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: HDR-to-SDR-macOS
        path: dist/HDR_to_SDR_Converter.dmg
